# Generated by Django 3.2.8 on 2021-11-24 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('size', models.TextField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra-Large')], default='M', max_length=2)),
                ('category', models.CharField(max_length=20)),
                ('isClosed', models.BooleanField(default=False)),
            ],
        ),
    ]
